#微服务注册到eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
#服务配置
server:
  port: 9002
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-system #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.98.131.149:3306/process?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: localhost
    port: 6379
jwt:
  config:
    key: saas-ihrm
    ttl: 3600000
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
